/**
 * Sample show data for the prototype.
 * Each entry = one exhibition at one place.
 * Later, this would come from APIs or a database.
 */
const SHOWS = [
  {
    id: "moma-ideas-of-africa",
    title: "Ideas of Africa",
    venueName: "MoMA",
    tier: "institution",
    neighborhood: "Midtown",
    address: "11 W 53rd St, New York, NY",
    lat: 40.7614,
    lng: -73.9776,
    startDate: "2026-03-15",
    endDate: "2026-08-23",
    openingReception: null,
    artists: [
      {
        name: "Njideka Akunyili Crosby",
        website: "https://www.njidekaakunyilicrosby.com/",
        artsyUrl: "https://www.artsy.net/artist/njideka-akunyili-crosby",
      },
    ],
  },
  {
    id: "whitney-biennial",
    title: "82nd Whitney Biennial",
    venueName: "Whitney Museum",
    tier: "institution",
    neighborhood: "Meatpacking",
    address: "99 Gansevoort St, New York, NY",
    lat: 40.7396,
    lng: -74.0089,
    startDate: "2026-03-08",
    endDate: "2026-08-23",
    openingReception: "2026-03-07T18:00",
    artists: [
      {
        name: "Kevin Beasley",
        website: null,
        artsyUrl: "https://www.artsy.net/artist/kevin-beasley",
      },
      {
        name: "Torkwase Dyson",
        website: "https://www.torkwasedyson.com/",
        artsyUrl: "https://www.artsy.net/artist/torkwase-dyson",
      },
    ],
  },
  {
    id: "met-gainsborough",
    title: "Gainsborough: The Fashion of Portraiture",
    venueName: "The Met",
    tier: "institution",
    neighborhood: "Upper East Side",
    address: "1000 5th Ave, New York, NY",
    lat: 40.7794,
    lng: -73.9632,
    startDate: "2026-02-12",
    endDate: "2026-05-02",
    openingReception: null,
    artists: [],
  },
  {
    id: "pace-maysha-mohamedi",
    title: "Maysha the Fool",
    venueName: "Pace Gallery",
    tier: "major-gallery",
    neighborhood: "Chelsea",
    address: "540 W 25th St, New York, NY",
    lat: 40.7501,
    lng: -74.0054,
    startDate: "2026-03-10",
    endDate: "2026-04-25",
    openingReception: "2026-03-06T18:00",
    artists: [
      {
        name: "Maysha Mohamedi",
        website: "https://www.mayshamohamedi.com/",
        artsyUrl: "https://www.artsy.net/artist/maysha-mohamedi",
      },
    ],
  },
  {
    id: "david-zwirner-crosby",
    title: "Coming Back to See Through, Again",
    venueName: "David Zwirner",
    tier: "major-gallery",
    neighborhood: "Chelsea",
    address: "519 W 19th St, New York, NY",
    lat: 40.7455,
    lng: -74.0062,
    startDate: "2026-04-03",
    endDate: "2026-05-30",
    openingReception: "2026-04-02T18:00",
    artists: [
      {
        name: "Njideka Akunyili Crosby",
        website: "https://www.njidekaakunyilicrosby.com/",
        artsyUrl: "https://www.artsy.net/artist/njideka-akunyili-crosby",
      },
    ],
  },
  {
    id: "casey-kaplan-beasley",
    title: "All I thought / I loved",
    venueName: "Casey Kaplan",
    tier: "major-gallery",
    neighborhood: "Chelsea",
    address: "121 W 27th St, New York, NY",
    lat: 40.7468,
    lng: -73.9917,
    startDate: "2026-05-14",
    endDate: "2026-07-24",
    openingReception: "2026-05-14T18:00",
    artists: [
      {
        name: "Kevin Beasley",
        website: null,
        artsyUrl: "https://www.artsy.net/artist/kevin-beasley",
      },
    ],
  },
  {
    id: "bushwick-gallery-organic",
    title: "Organic Elegance",
    venueName: "Bushwick Gallery",
    tier: "independent",
    neighborhood: "Bushwick",
    address: "22 Fayette St, Brooklyn, NY",
    lat: 40.7054,
    lng: -73.9332,
    startDate: "2026-05-14",
    endDate: "2026-06-14",
    openingReception: "2026-05-14T18:00",
    artists: [
      {
        name: "Local emerging artists (group show)",
        website: null,
        artsyUrl: null,
      },
    ],
  },
  {
    id: "greenpoint-open-studio",
    title: "Greenpoint Open Studios",
    venueName: "Greenpoint Studios",
    tier: "open-studio",
    neighborhood: "Greenpoint",
    address: "67 West St, Brooklyn, NY",
    lat: 40.7319,
    lng: -73.9587,
    startDate: "2026-06-06",
    endDate: "2026-06-07",
    openingReception: "2026-06-06T12:00",
    artists: [
      {
        name: "Various artists",
        website: "https://greenpointopenstudios.org/",
        artsyUrl: null,
      },
    ],
  },
  {
    id: "ridgewood-pop-up",
    title: "Ridgewood Print Fair",
    venueName: "The Ridgewood Space",
    tier: "open-studio",
    neighborhood: "Ridgewood",
    address: "1717 Troutman St, Queens, NY",
    lat: 40.7068,
    lng: -73.9215,
    startDate: "2026-05-23",
    endDate: "2026-05-24",
    openingReception: "2026-05-23T14:00",
    artists: [
      {
        name: "Independent printmakers",
        website: null,
        artsyUrl: null,
      },
    ],
  },
  {
    id: "amant-kim-gordon",
    title: "Count Your Chickens",
    venueName: "Amant",
    tier: "institution",
    neighborhood: "Williamsburg",
    address: "306 Maujer St, Brooklyn, NY",
    lat: 40.7088,
    lng: -73.9338,
    startDate: "2026-03-19",
    endDate: "2026-08-16",
    openingReception: "2026-03-19T18:00",
    artists: [
      {
        name: "Kim Gordon",
        website: "https://www.kimgordon.com/",
        artsyUrl: "https://www.artsy.net/artist/kim-gordon",
      },
    ],
  },
  {
    id: "amant-folded-group",
    title: "Folded Group",
    venueName: "Amant",
    tier: "institution",
    neighborhood: "Williamsburg",
    address: "312 Maujer St, Brooklyn, NY",
    lat: 40.7085,
    lng: -73.9342,
    startDate: "2026-03-19",
    endDate: "2026-05-17",
    openingReception: "2026-03-19T18:00",
    artists: [
      {
        name: "Bill Nace",
        website: null,
        artsyUrl: null,
      },
      {
        name: "Kim Gordon",
        website: "https://www.kimgordon.com/",
        artsyUrl: "https://www.artsy.net/artist/kim-gordon",
      },
    ],
  },
  {
    id: "amant-christelle-oyiri",
    title: "Belief May Vary",
    venueName: "Amant",
    tier: "institution",
    neighborhood: "Williamsburg",
    address: "315 Maujer St, Brooklyn, NY",
    lat: 40.7083,
    lng: -73.9335,
    startDate: "2026-03-19",
    endDate: "2026-08-16",
    openingReception: "2026-03-19T18:00",
    artists: [
      {
        name: "Christelle Oyiri",
        website: "https://www.christelleoyiri.com/",
        artsyUrl: "https://www.artsy.net/artist/christelle-oyiri",
      },
    ],
  },
  {
    id: "amant-cfgny",
    title: "Puddles into Pond",
    venueName: "Amant",
    tier: "independent",
    neighborhood: "Williamsburg",
    address: "315 Maujer St, Brooklyn, NY",
    lat: 40.7081,
    lng: -73.9331,
    startDate: "2026-03-19",
    endDate: "2026-08-16",
    openingReception: "2026-05-17T14:00",
    artists: [
      {
        name: "CFGNY",
        website: "https://www.cfgny.net/",
        artsyUrl: null,
      },
    ],
  },
  {
    id: "awita-euphoria",
    title: "Euphoria",
    venueName: "Awita New York Studio",
    tier: "independent",
    neighborhood: "Williamsburg",
    address: "274 S 2nd St, Brooklyn, NY",
    lat: 40.7108,
    lng: -73.9589,
    startDate: "2026-06-04",
    endDate: "2026-07-04",
    openingReception: "2026-06-04T18:00",
    artists: [
      {
        name: "International group of artists",
        website: "https://www.awitanewyork.com/",
        artsyUrl: null,
      },
    ],
  },
];

const TIER_LABELS = {
  institution: "Major museum",
  "major-gallery": "Major gallery",
  independent: "Independent gallery",
  "open-studio": "Open studio / pop-up",
};

const TIER_COLORS = {
  institution: "#1e3a5f",
  "major-gallery": "#7c3aed",
  independent: "#059669",
  "open-studio": "#ea580c",
};
